- hosts: all
  become: yes
  tasks:

   - name: Unarchive file to remote server
     unarchive:
       src: https://github.com/prometheus/node_exporter/releases/download/v{{exporter_version}}/node_exporter-{{exporter_version}}.linux-amd64.tar.gz
       dest: /tmp/
       mode: 0755
       remote_src: yes

   - name: Copy service file to remote server
     copy:
       src: ./node_exporter.service
       dest: /etc/systemd/system/

   - name: Copy node_exporter to bin folder
     copy:
       remote_src: yes
       src: /tmp/node_exporter-{{exporter_version}}.linux-amd64/node_exporter
       dest: /usr/local/bin
       mode: +x

   - name: Add the user 'node_exporter'
     user:
       name: node_exporter
       comment: node_exporter user
       create_home: no
       home: /
       shell: /bin/false node_exporter
       append: yes

   - name: Start service node_exporter
     systemd:
       name: node_exporter
       daemon_reload: yes
       state: started
